### ISSUE TITLE
When is it ready to get supported preview size?

### ISSUE THREAD

**Issue by quocnhat7** [jiangdongguo/AndroidUSBCamera#126]
Hi,
List<com.serenegiant.usb.Size> list = cameraHelper.getSupportedPreviewSizes();
May I know when this method return NOT NULL?
Now in onAttachDev() or onConnectDev(), I called that method but return null.
It is strange. In your source, I see "supported preview sizes" will be saved in open() method, so at onConnectDev() I can receive data.

**Comment by jiangdongguo** [comment]
In onConnectDev and try to delay one seconds.

**Comment by quocnhat7** [comment]
ok, can call after ~1sec. Perhaps because of threading.
