### ISSUE TITLE
2.3.0 Release not build

### ISSUE THREAD

**Issue by RiponDas** [jiangdongguo/AndroidUSBCamera#137]
Release 2.3.0 doesn't build in android studio after opening shows this error message. It occurs due to compilation error for kotlin may be.
Error: Content is not allowed in prolog.

`> Configure project : 
[Fatal Error] kotlin-reflect-1.2.0.pom:2:1: Content is not allowed in prolog.
[Fatal Error] databinding-common-3.2.1.pom:2:1: Content is not allowed in prolog.
[Fatal Error] baseLibrary-3.2.1.pom:2:1: Content is not allowed in prolog.
[Fatal Error] antlr4-4.5.3.pom:2:1: Content is not allowed in prolog.
[Fatal Error] juniversalchardet-1.0.3.pom:2:1: Content is not allowed in prolog.
[Fatal Error] javapoet-1.8.0.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.
`
If there use Jython then please anyone tell me what should I do.
Please don't feel annoyed for the rapid question.

Thanks.....@jiangdongguo

**Comment by quocnhat7** [comment]
You should clone sample app, then link to latest lib 2.3.0. If not work, it might be because of lib.
If ok, so it is because of your app dependencies.

If you link back to old lib 2.2.8, is it ok?

**Comment by RiponDas** [comment]
No I have cloned this new lib 2.3.0 but show the error.

Content is not allowed in prolog.

**Comment by RiponDas** [comment]
@jiangdongguo 
Please help me with the issue I faced. 

ERROR: Content is not allowed in prolog.

I can't resolve this problem until now.  Please help me.
