### ISSUE TITLE
检测不到摄像头，打开应用无法预览

### ISSUE THREAD

**Issue by ThanksGuo** [jiangdongguo/AndroidUSBCamera#150]

**Comment by jersun** [comment]
I have the same question as you, have you solved it?

**Comment by ThanksGuo** [comment]
兄弟，我不知道你的原因是什么。我的手机是定制的，所以系统有点坑。在USBMonitor.getDeviceList(filters)方法中会去创建“/storage/emulated/0/USBCamera/failed_devices.txt”文件。问题就出在这儿。所以我先去穿件路径“/storage/emulated/0/USBCamera/”，然后再去创建文件“failed_devices.txt”。希望能帮助到你。

**Comment by jersun** [comment]
解决了，谢谢
