### ISSUE TITLE
No Image.

### ISSUE THREAD

**Issue by cp0418** [jiangdongguo/AndroidUSBCamera#200]
When I connected with Logitech camera  It's working but when I connected with Synchronized USB2.0 Stereo Camera It doesn't work then I tried to change frame format from MJPEG to YUYV but still not work it's connecting but no image.
![image](https://user-images.githubusercontent.com/52272847/72252679-5a54e800-3632-11ea-8345-2d57acaf4326.png)

**Comment by jiangdongguo** [comment]
please try to update to 2.3.2

**Comment by cp0418** [comment]
You mean " classpath 'com.android.tools.build:gradle:3.5.2' " right ?

**Comment by cp0418** [comment]
> please try to update to 2.3.2

You mean " classpath 'com.android.tools.build:gradle:3.5.2' " right ?

**Comment by jiangdongguo** [comment]
no image perhaps because of creating file directory failed.On 2.3.2,I fixed it.

**Comment by cp0418** [comment]
I think the problem is my camera.It supports YUY2. What do you think about this?
![image](https://user-images.githubusercontent.com/52272847/72598312-21728700-3942-11ea-88e2-947f9719bf5a.png)

**Comment by jiangdongguo** [comment]
nothing different. please using mjpeg and update the lib to 2.3.2,and have a try.

**Comment by cp0418** [comment]
I tried and there is an error.
> Could not GET 'https://jitpack.io/com/github/jiangdongguo/libutils/2.3.2/libutils-2.3.2.pom'. Received status code 401 from server: Unauthorized
Enable Gradle 'offline mode' and sync project

I really appreciate you. I am very new about it. Thank you so much for your help.

**Comment by cp0418** [comment]
Thank you so much for your help.
