### ISSUE TITLE
Bitmap

### ISSUE THREAD

**Issue by AsmodanPushPlay** [jiangdongguo/AndroidUSBCamera#211]
I would like to ask if there is a way to get a Bitmap directly from the Preview without saving an image first or generating a Screenshot. I need to analyze some frames from the Preview and saving an image and converting it is bad practice. 

A regular TextureView has the getBitmap method, which makes it very easy, but I could not find a good solution for the USBCamera Preview.

**Comment by BernieMadoff** [comment]
what did you end up doing for this? bitmap factory always gives a null bitmap for me
