### ISSUE TITLE
stopPreview 崩溃的问题有人解决了吗，急急急！！！

### ISSUE THREAD

**Issue by lliecho** [jiangdongguo/AndroidUSBCamera#214]
调用stopPreview出现概率性崩溃

**Comment by zyowo** [comment]
我也在困扰这个问题，拔掉设备或者切换设备的时候概率性崩溃

**Comment by wzjsword** [comment]
原作者issue里有人提出并解决了，去翻翻把

**Comment by lliecho** [comment]
> 原作者issue里有人提出并解决了，去翻翻把

翻了很多遍也没有找到呀

**Comment by wzjsword** [comment]
> > 原作者issue里有人提出并解决了，去翻翻把
> 
> 翻了很多遍也没有找到呀

https://github.com/saki4510t/UVCCamera/pull/520

**Comment by lliecho** [comment]
> > > 原作者issue里有人提出并解决了，去翻翻把
> > 
> > 
> > 翻了很多遍也没有找到呀
> 
> [saki4510t/UVCCamera#520](https://github.com/saki4510t/UVCCamera/pull/520)

感谢，感谢！！

**Comment by lliecho** [comment]
> > > 原作者issue里有人提出并解决了，去翻翻把
> > 
> > 
> > 翻了很多遍也没有找到呀
> 
> [saki4510t/UVCCamera#520](https://github.com/saki4510t/UVCCamera/pull/520)

感谢，感谢！！
