### ISSUE TITLE
 com.serenegiant:common:4.1.1. 无法下载，编译过不去。。。

### ISSUE THREAD

**Issue by jjjjbababy** [jiangdongguo/AndroidUSBCamera#224]
ERROR: Unable to resolve dependency for ':libusbcamera@debug/compileClasspath': Could not resolve com.serenegiant:common:4.1.1.

**Comment by kevin-lemon** [comment]
同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。

**Comment by jjjjbababy** [comment]
> 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。

我也试了把 aar直接放在libs下，也不管用。。

**Comment by kevin-lemon** [comment]
> > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> 
> 我也试了把 aar直接放在libs下，也不管用。。

我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了

**Comment by kevin-lemon** [comment]
> > > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> > 
> > 
> > 我也试了把 aar直接放在libs下，也不管用。。
> 
> 我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了

搞定

**Comment by jjjjbababy** [comment]
> > > > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> > > 
> > > 
> > > 我也试了把 aar直接放在libs下，也不管用。。
> > 
> > 
> > 我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了
> 
> 搞定

咋搞的

**Comment by kevin-lemon** [comment]
> > > > > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> > > > 
> > > > 
> > > > 我也试了把 aar直接放在libs下，也不管用。。
> > > 
> > > 
> > > 我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了
> > 
> > 
> > 搞定
> 
> 咋搞的

clone下来项目，吧libusbcamera 单独引用进去，然后修改libusbcamera的gradle，弄成本地aar

**Comment by jjjjbababy** [comment]
> > > > > > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> > > > > 
> > > > > 
> > > > > 我也试了把 aar直接放在libs下，也不管用。。
> > > > 
> > > > 
> > > > 我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了
> > > 
> > > 
> > > 搞定
> > 
> > 
> > 咋搞的
> 
> clone下来项目，吧libusbcamera 单独引用进去，然后修改libusbcamera的gradle，弄成本地aar

我把那个common-2.12.4.aar  下载下来了 放到libs里的 ，
implementation fileTree(dir: 'libs', include: ['*.jar','*.aar'])这个写了 ，还是不管用

**Comment by jjjjbababy** [comment]
implementation fileTree(dir: 'libs', include: ['*.jar','*.aar'])

**Comment by kevin-lemon** [comment]
> > > > > > > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> > > > > > 
> > > > > > 
> > > > > > 我也试了把 aar直接放在libs下，也不管用。。
> > > > > 
> > > > > 
> > > > > 我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了
> > > > 
> > > > 
> > > > 搞定
> > > 
> > > 
> > > 咋搞的
> > 
> > 
> > clone下来项目，吧libusbcamera 单独引用进去，然后修改libusbcamera的gradle，弄成本地aar
> 
> 我把那个common-2.12.4.aar 下载下来了 放到libs里的 ，
> implementation fileTree(dir: 'libs', include: ['_.jar','_.aar'])这个写了 ，还是不管用

你是放到libusbcamera下面？

**Comment by jjjjbababy** [comment]
> > > > > > > > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> > > > > > > 
> > > > > > > 
> > > > > > > 我也试了把 aar直接放在libs下，也不管用。。
> > > > > > 
> > > > > > 
> > > > > > 我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了
> > > > > 
> > > > > 
> > > > > 搞定
> > > > 
> > > > 
> > > > 咋搞的
> > > 
> > > 
> > > clone下来项目，吧libusbcamera 单独引用进去，然后修改libusbcamera的gradle，弄成本地aar
> > 
> > 
> > 我把那个common-2.12.4.aar 下载下来了 放到libs里的 ，
> > implementation fileTree(dir: 'libs', include: ['_.jar','_.aar'])这个写了 ，还是不管用
> 
> 你是放到libusbcamera下面？

是啊，libusbcamera下  src下 的libs里

**Comment by kevin-lemon** [comment]
> > > > > > > > > 同样，我也碰到了，我打算把库下载下来，再把这个包下载下来手动配置了。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我也试了把 aar直接放在libs下，也不管用。。
> > > > > > > 
> > > > > > > 
> > > > > > > 我估计把他的这个项目的库下载到本地，然后修改他引用包里的配置，配置成本地AAR就好了
> > > > > > 
> > > > > > 
> > > > > > 搞定
> > > > > 
> > > > > 
> > > > > 咋搞的
> > > > 
> > > > 
> > > > clone下来项目，吧libusbcamera 单独引用进去，然后修改libusbcamera的gradle，弄成本地aar
> > > 
> > > 
> > > 我把那个common-2.12.4.aar 下载下来了 放到libs里的 ，
> > > implementation fileTree(dir: 'libs', include: ['_.jar','_.aar'])这个写了 ，还是不管用
> > 
> > 
> > 你是放到libusbcamera下面？
> 
> 是啊，libusbcamera下 src下 的libs里

我刚编译通过的。加我QQ765002108

**Comment by jjjjbababy** [comment]
solved

**Comment by Dreamskya** [comment]
@jjjjbababy 怎么搞定的，我也是你这种做法，还是不行。
