### ISSUE TITLE
Android10有预览成功的么？

### ISSUE THREAD

**Issue by 41108871** [jiangdongguo/AndroidUSBCamera#232]
Android10平台上预览黑屏。有其它朋友有没有在Q平台上USB CAMERA预览成功了的？

**Comment by 41108871** [comment]
Just change the buffer size in #define LIBUVC_NUM_TRANSFER_BUFS 5

Now I can preview the usb camera on my Android 10.

**Comment by pjj0601** [comment]
能不能说的更详细一些，谢谢

**Comment by pjj0601** [comment]
> 只需在#define LIBUVC_NUM_TRANSFER_BUFS 5中更改缓冲区大小即可
> 
> 现在，我可以在Android 10上预览USB相机了。

能否更新一个支持安卓10的版本

**Comment by 41108871** [comment]
\libuvc\include\libuvc\libuvc_internal.h  这个文件中修改 #define LIBUVC_NUM_TRANSFER_BUFS 10
其它的跟github上的代码一样就行了。

**Comment by sandsboy** [comment]
target-sdk 设置成27就可以了
