### ISSUE TITLE
运行中jni 部分报错导致程序崩溃

### ISSUE THREAD

**Issue by xuantiandou** [jiangdongguo/AndroidUSBCamera#290]
pid: 9025, tid: 9086, name: Thread-5  >>> com.zjzl.zjzlnetbroadcast <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: obj == null'
    r0  00000000  r1  0000237e  r2  00000006  r3  b0fa3918
    r4  00002341  r5  0000237e  r6  8f98174c  r7  0000010c
    r8  0000000b  r9  aef90740  r10 0000076f  r11 aed2107e
    ip  00000041  sp  8f981738  lr  b0f320e5  pc  b0f29e72

backtrace:
    #00 pc 0001ce72  /system/lib/libc.so (abort+62)
    #01 pc 00356e7f  /system/lib/libart.so (art::Runtime::Abort(char const*)+798)
    #02 pc 000071c7  /system/lib/libbase.so (android::base::LogMessage::~LogMessage()+502)
    #03 pc 00235d1f  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1246)
    #04 pc 000114f0  /data/app/com.zjzl.zjzlnetbroadcast-08r0PNnrzowYfh7qYNt7vw==/lib/arm/libUVCCamera.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+52)
    #05 pc 0001140c  /data/app/com.zjzl.zjzlnetbroadcast-08r0PNnrzowYfh7qYNt7vw==/lib/arm/libUVCCamera.so (UVCPreview::do_capture_callback(_JNIEnv*, uvc_frame*)+244)
    #06 pc 000110bc  /data/app/com.zjzl.zjzlnetbroadcast-08r0PNnrzowYfh7qYNt7vw==/lib/arm/libUVCCamera.so (UVCPreview::do_capture(_JNIEnv*)+144)
    #07 pc 00010b04  /data/app/com.zjzl.zjzlnetbroadcast-08r0PNnrzowYfh7qYNt7vw==/lib/arm/libUVCCamera.so (UVCPreview::capture_thread_func(void*)+64)
    #08 pc 00063c15  /system/lib/libc.so (__pthread_start(void*)+22)
    #09 pc 0001e065  /system/lib/libc.so (__start_thread+22)

**Comment by CrossYourSoul** [comment]
请问楼主解决了吗..我也碰到了 不是稳定复现
