### ISSUE TITLE
When recording on Samsung S10 video is blue

### ISSUE THREAD

**Issue by ToysoftInc** [jiangdongguo/AndroidUSBCamera#293]
Why is the video recorded blue?
I'm just compiling the sample app.  I did try one of the user suggestions for changing the format and either works.

        mCameraHelper.setDefaultFrameFormat( UVCCamera.PIXEL_FORMAT_YUV);
        mCameraHelper.setDefaultFrameFormat(UVCCamera.PIXEL_FORMAT_YUV420SP);

Also in the recorded video there is a green bar.

Taking a picture is ok.

Thanks

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
