### ISSUE TITLE
集成com.serenegiant:common这个库到自己项目，编译时候报了这个duplicate value for resource 'attr/orientation' with config 

### ISSUE THREAD

**Issue by shiduan** [jiangdongguo/AndroidUSBCamera#296]
请问作者有没有解决思路，我集成到自己项目的时候，定位到是集成这个库后会报资源重复问题
compile("com.serenegiant:common:2.12.4") {
        exclude module: 'support-v4'
    }
duplicate value for resource 'attr/orientation' with config

**Comment by shiduan** [comment]
原因是com.serenegiant:common:2.12.4内部自定义了attr/orientation，和自己项目冲突后，后来解决是下载到common的源码进行修改，注释该主题和相关的引用

**Comment by quanquan-dane** [comment]
您好，你这边视频录制可以么？我这边Android5.1.1的点击demo视频录制弹出start recording，，然后就闪退了
