### ISSUE TITLE
点击拍照没有执行回调

### ISSUE THREAD

**Issue by summeryan** [jiangdongguo/AndroidUSBCamera#300]
你好  我运行你的项目 点击拍照 但是没有执行onCaptureResult方法的回调，log里也没有报错 会是什么原因呢

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try

**Comment by simsimst** [comment]
您好，我用的3.3.3版本。如果使用cameraClient，拍照拍视频没有问题。改成MultiCameraClient，用CameraUvc类进行拍照拍视频不执行回调，也没有文件产生，请问这是为什么呢。两种Client都可以preview成功，CameraView用的都是TextureView，CameraRequest一样 @jiangdongguo
