### ISSUE TITLE
点击录制，出现start recording  然后1秒后闪退

### ISSUE THREAD

**Issue by quanquan-dane** [jiangdongguo/AndroidUSBCamera#301]
使用的是Android5.1.1环境运行如下配置的包，不能录像，开启录像后1秒闪退，抛出一个未知异常

androidXVersion = '1.1.0'  // variable that can be referenced to keep support libs consistent
    commonLibVersion= '4.1.1'
    versionCompiler = 28
    // when target=27, 9.0 is ok
    versionTarget = 27
    // if hope supporting 4.4
    // please modify it to 16
    minSdkVersion = 21
    versionCode = 99
    versionNameString = '1.2.1.20200414'
    javaSourceCompatibility = JavaVersion.VERSION_1_8
    javaTargetCompatibility = JavaVersion.VERSION_1_8

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
