### ISSUE TITLE
开启预览后没有图像  十几秒后崩溃闪退

### ISSUE THREAD

**Issue by mzc007** [jiangdongguo/AndroidUSBCamera#305]
01-25 17:41:21.507   492   548 I ActivityManager: Start proc 2629:com.frasker.detection/1000 for service com.frasker.detection/.gpio.GpioService
01-25 17:41:21.507  2629  2629 I art     : Late-enabling -Xcheck:jni
01-25 17:41:21.508  2629  2629 E art     : setrlimit(RLIMIT_CORE) failed for pid 2629: Operation not permitted
01-25 17:41:21.649  2629  2629 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1421 android.content.ContextWrapper.bindService:636 android.speech.tts.TextToSpeech.connectToEngine:810 android.speech.tts.TextToSpeech.initTts:780 android.speech.tts.TextToSpeech.<init>:733
01-25 17:41:25.541  2629  2629 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-25 17:41:25.569  2629  2656 E WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
01-25 17:41:25.578  2629  2656 I MediaCodec: callingProcessName:com.frasker.detection
01-25 17:41:25.583  2629  2657 I OMXClient: MuxOMX ctor
01-25 17:41:25.583  2629  2657 I ACodec  : onAllocateComponent:6703 mSoftCodecPref:0 componentName:
01-25 17:41:25.585  2629  2657 I ACodec  : onAllocateComponent:6734 mSoftCodecPref:0 componentName:OMX.google.mp3.decoder
01-25 17:41:25.627   492   548 W BroadcastQueue: Permission Denial: broadcasting Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } from null (pid=-1, uid=-1) requires com.tencent.bugly.BuglyBroadcastReceiver.permission due to registered receiver BroadcastFilter{781646b u0 ReceiverList{5057dba 2629 com.frasker.detection/1000/u0 remote:975fee5}}
01-25 17:41:25.784  2629  2629 D FaceSDKNative: faceDetectionModelPath: /storage/B911-18F8/USBCamera/model
01-25 17:41:25.795  2629  2629 D FaceSDKNative: createFromFile 
01-25 17:41:25.803  2629  2629 D FaceSDKNative: createSession 
01-25 17:41:25.803  2629  2629 D FaceSDKNative: getSessionInput
01-25 17:41:25.919  2629  2629 D lalala  : initCamera
01-25 17:41:25.927  2629  2629 V CameraThread: getHandler:
01-25 17:41:25.929  2629  2629 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1357 android.content.ContextWrapper.startService:613 com.frasker.detection.MainActivity.onCreate:219 android.app.Activity.performCreate:6709 android.app.Instrumentation.callActivityOnCreate:1118 
01-25 17:41:25.959  2629  2700 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-25 17:41:26.176  2629  2629 D GRALLOC-ROCKCHIP: enter, w : 576, h : 576, format : 0x1, usage : 0x100.
01-25 17:41:26.182  2629  2629 D value   : acc:3.0 lux:2600.0
01-25 17:41:27.167  2629  2698 D devList : 1
01-25 17:41:27.173  2629  2698 D devList : UsbDevice[mName=/dev/bus/usb/002/002,mVendorId=6257,mProductId=304,mClass=239,mSubclass=2,mProtocol=1,mManufacturerName=USB HJ-WDR,mProductName=USB HJ-WDR,mVersion=2.0,mSerialNumber=USB HJ-WDR,mConfigurations=[
01-25 17:41:27.173  2629  2698 D devList : UsbConfiguration[mId=1,mName=null,mAttributes=128,mMaxPower=250,mInterfaces=[
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=0,mAlternateSetting=0,mName=USB HJ-WDR,mClass=14,mSubclass=1,mProtocol=0,mEndpoints=[
01-25 17:41:27.173  2629  2698 D devList : UsbEndpoint[mAddress=131,mAttributes=3,mMaxPacketSize=16,mInterval=6]]
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=1,mAlternateSetting=0,mName=USB HJ-WDR,mClass=14,mSubclass=2,mProtocol=0,mEndpoints=[]
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=1,mAlternateSetting=1,mName=null,mClass=14,mSubclass=2,mProtocol=0,mEndpoints=[
01-25 17:41:27.173  2629  2698 D devList : UsbEndpoint[mAddress=129,mAttributes=5,mMaxPacketSize=128,mInterval=1]]
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=1,mAlternateSetting=2,mName=null,mClass=14,mSubclass=2,mProtocol=0,mEndpoints=[
01-25 17:41:27.173  2629  2698 D devList : UsbEndpoint[mAddress=129,mAttributes=5,mMaxPacketSize=256,mInterval=1]]
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=1,mAlternateSetting=3,mName=null,mClass=14,mSubclass=2,mProtocol=0,mEndpoints=[
01-25 17:41:27.173  2629  2698 D devList : UsbEndpoint[mAddress=129,mAttributes=5,mMaxPacketSize=800,mInterval=1]]
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=1,mAlternateSetting=4,mName=null,mClass=14,mSubclass=2,mProtocol=0,mEndpoints=[
01-25 17:41:27.173  2629  2698 D devList : UsbEndpoint[mAddress=129,mAttributes=5,mMaxPacketSize=2848,mInterval=1]]
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=1,mAlternateSetting=5,mName=null,mClass=14,mSubclass=2,mProtocol=0,mEndpoints=[
01-25 17:41:27.173  2629  2698 D devList : UsbEndpoint[mAddress=129,mAttributes=5,mMaxPacketSize=4896,mInterval=1]]
01-25 17:41:27.173  2629  2698 D devList : UsbInterface[mId=1,mAlternateSetting=6,mName=null,mClass=14,mSubclass=2,mProtocol=0,mEndpoints=[
01-25 17:41:27.173  2629  2698 D devList : UsbEndpoint[mAddress=129,mAttributes=5,mMaxPacketSize=5120,mInterval=1]]]]
01-25 17:41:27.241  2629  2698 D UsbDeviceConnectionJNI: close
01-25 17:41:27.242  2629  2698 I USBMonitor: name=/dev/bus/usb/002/002,desc=40,busnum=2,devnum=2,rawDesc=[B@526b50b
01-25 17:41:27.242  2629  2699 V CameraThread: handleOpen:
01-25 17:41:27.242  2629  2699 V CameraThread: handleClose:
01-25 17:41:27.261  2629  2699 D UsbDeviceConnectionJNI: close
01-25 17:41:27.261  2629  2699 I libusb/core: [2699*core.c:2085:libusb_init2]:libusb v1.0.19.10903
01-25 17:41:27.261  2629  2699 I libusb/usbfs: [2699*android_usbfs.c:504:op_init2]:start up hotplug event handler
01-25 17:41:27.261  2629  2699 I libusb/usbfs: [2699*android_usbfs.c:512:op_init2]:call android_scan_devices
01-25 17:41:27.299  2629  2699 I AbsUVCCameraHandler: supportedSize:{"formats":[{"index":1,"type":6,"default":1,"size":["640x480","1024x768","1280x960","1280x720","1920x1080","320x240","800x600","352x288"]},{"index":2,"type":4,"default":1,"size":["640x480","1920x1080","1024x768","320x240","800x600","1280x720","1280x960","352x288"]}]}
01-25 17:41:27.304  2629  2703 I mali_so : [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 978; [Func] : base_context_deal_with_version_affairs_rk_ext;
01-25 17:41:27.304  2629  2703 I mali_so : arm_release_ver of this mali_so is 'r14p0-01rel0', rk_so_ver is '5@0'.
01-25 17:41:27.304  2629  2703 D mali_so : [File] : hardware/arm/maliT760/driver/product/base/src/mali_base_kbase.c; [Line] : 983; [Func] : base_context_deal_with_version_affairs_rk_ext;
01-25 17:41:27.304  2629  2703 D mali_so : current process is NOT sf, to bail out.
01-25 17:41:27.307  2629  2703 I OpenGLRenderer: Initialized EGL, version 1.4
01-25 17:41:27.307  2629  2703 D OpenGLRenderer: Swap behavior 1
01-25 17:41:27.317  2629  2703 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
01-25 17:41:27.328  2629  2703 D GRALLOC-ROCKCHIP: enter, w : 106, h : 39, format : 0x1, usage : 0xb00.
01-25 17:41:27.337  2629  2703 D GRALLOC-ROCKCHIP: enter, w : 106, h : 39, format : 0x1, usage : 0xb00.
01-25 17:41:36.436  2629  2629 I Choreographer: Skipped 615 frames!  The application may be doing too much work on its main thread.
01-25 17:41:36.488  2629  2703 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
01-25 17:41:36.562  2629  2629 I UVCCameraTextureView: onSurfaceTextureAvailable:android.graphics.SurfaceTexture@fe65489
01-25 17:41:36.563  2629  2629 V UVCCameraTextureView: RenderThread#getHandler:
01-25 17:41:36.563  2629  2729 D UVCCameraTextureView: RenderThread started
01-25 17:41:36.563  2629  2729 V UVCCameraTextureView: RenderThread#init:
01-25 17:41:36.566  2629  2729 D EGLBase14: EGLContext created, client version 3
01-25 17:41:36.567  2629  2729 E BufferQueueProducer: [SurfaceTexture-0-2629-0] connect: already connected (cur=1 req=1)
01-25 17:41:36.567  2629  2729 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
01-25 17:41:36.571  2629  2629 V UVCCameraTextureView: getSurface:hasSurface=true
01-25 17:41:36.571  2629  2629 V UVCCameraTextureView: getPreviewTexture:
01-25 17:41:36.572  2629  2729 I UVCCameraTextureView: RenderThread#updatePreviewSurface:
01-25 17:41:36.573  2629  2729 V UVCCameraTextureView: updatePreviewSurface:tex_id=1
01-25 17:41:36.580  2629  2703 D GRALLOC-ROCKCHIP: enter, w : 240, h : 320, format : 0x1, usage : 0xb00.
01-25 17:41:36.585  2629  2703 D GRALLOC-ROCKCHIP: enter, w : 240, h : 320, format : 0x1, usage : 0xb00.
01-25 17:41:36.603  2629  2703 D GRALLOC-ROCKCHIP: enter, w : 240, h : 320, format : 0x1, usage : 0xb00.
01-25 17:41:38.553  2629  2703 D GRALLOC-ROCKCHIP: enter, w : 240, h : 320, format : 0x1, usage : 0xb00.
01-25 17:41:39.594  2629  2629 I Timer-0 : type=1400 audit(0.0:237): avc: denied { write } for name="direction" dev="sysfs" ino=22101 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
01-25 17:41:49.452  2629  2773 W System.err: java.net.SocketTimeoutException: timeout
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
01-25 17:41:49.452  2629  2773 W System.err: 	at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.frasker.detection.utils.HttpConnectionUtil$1.call(HttpConnectionUtil.java:53)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.frasker.detection.utils.HttpConnectionUtil$1.call(HttpConnectionUtil.java:27)
01-25 17:41:49.453  2629  2773 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-25 17:41:49.453  2629  2773 W System.err: 	at java.lang.Thread.run(Thread.java:761)
01-25 17:41:49.453  2629  2773 W System.err: Caused by: java.net.SocketException: Socket closed
01-25 17:41:49.453  2629  2773 W System.err: 	at java.net.SocketInputStream.socketRead0(Native Method)
01-25 17:41:49.453  2629  2773 W System.err: 	at java.net.SocketInputStream.read(SocketInputStream.java:151)
01-25 17:41:49.453  2629  2773 W System.err: 	at java.net.SocketInputStream.read(SocketInputStream.java:120)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
01-25 17:41:49.453  2629  2773 W System.err: 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
01-25 17:41:49.453  2629  2773 W System.err: 	... 14 more
01-25 17:41:57.475  2629  2783 D TelephonyManager: setDataEnabled: enabled=false
01-25 17:41:57.646  2629  2801 D SocketEmit: resultio.socket.engineio.client.EngineIOException: xhr poll error
01-25 17:41:58.102  2629  2634 I art     : Do partial code cache collection, code=19KB, data=30KB
01-25 17:41:58.103  2629  2634 I art     : After code cache collection, code=19KB, data=30KB
01-25 17:41:58.103  2629  2634 I art     : Increasing code cache capacity to 128KB
01-25 17:41:58.481  2629  2783 D TelephonyManager: setDataEnabled: enabled=true
01-25 17:41:58.483  2629  2783 D Login   : connect timed out
01-25 17:41:58.483  2629  2783 D Login   : java.net.SocketTimeoutException: connect timed out
01-25 17:41:58.483  2629  2783 W System.err: java.net.SocketTimeoutException: connect timed out
01-25 17:41:58.483  2629  2783 W System.err: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
01-25 17:41:58.484  2629  2783 W System.err: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
01-25 17:41:58.484  2629  2783 W System.err: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
01-25 17:41:58.484  2629  2783 W System.err: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
01-25 17:41:58.484  2629  2783 W System.err: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
01-25 17:41:58.484  2629  2783 W System.err: 	at java.net.Socket.connect(Socket.java:605)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.Connection.connect(Connection.java:172)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.frasker.detection.login.LoginManager$1.call(LoginManager.java:135)
01-25 17:41:58.484  2629  2783 W System.err: 	at com.frasker.detection.login.LoginManager$1.call(LoginManager.java:116)
01-25 17:41:58.484  2629  2783 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-25 17:41:58.484  2629  2783 W System.err: 	at java.lang.Thread.run(Thread.java:761)
01-25 17:41:58.485  2629  2629 W System.err: org.json.JSONException: End of input at character 0 of 
01-25 17:41:58.485  2629  2629 W System.err: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
01-25 17:41:58.485  2629  2629 W System.err: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
01-25 17:41:58.486  2629  2629 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:156)
01-25 17:41:58.486  2629  2629 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:173)
01-25 17:41:58.486  2629  2629 W System.err: 	at com.frasker.detection.login.LoginManager.init(LoginManager.java:73)
01-25 17:41:58.486  2629  2629 W System.err: 	at com.frasker.detection.MainActivity.startLogin(MainActivity.java:170)
01-25 17:41:58.486  2629  2629 W System.err: 	at com.frasker.detection.MainActivity.initCheck(MainActivity.java:162)
01-25 17:41:58.486  2629  2629 W System.err: 	at com.frasker.detection.MainActivity.access$100(MainActivity.java:80)
01-25 17:41:58.486  2629  2629 W System.err: 	at com.frasker.detection.MainActivity$1.handleMessage(MainActivity.java:122)
01-25 17:41:58.486  2629  2629 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-25 17:41:58.486  2629  2629 W System.err: 	at android.os.Looper.loop(Looper.java:154)
01-25 17:41:58.486  2629  2629 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
01-25 17:41:58.486  2629  2629 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
01-25 17:41:58.486  2629  2629 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
01-25 17:41:58.486  2629  2629 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
01-25 17:42:00.174  2629  2918 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
01-25 17:42:00.178  2629  2919 I MediaCodec: callingProcessName:com.frasker.detection
01-25 17:42:00.179  2629  2918 I H264EncodeConsumer: bitrate= 2.20[Mbps]
01-25 17:42:00.180  2629  2918 I MediaCodec: callingProcessName:com.frasker.detection
01-25 17:42:00.180  2629  2922 I OMXClient: MuxOMX ctor
01-25 17:42:00.180  2629  2922 I ACodec  : onAllocateComponent:6703 mSoftCodecPref:0 componentName:OMX.google.aac.encoder
01-25 17:42:00.180  2629  2922 I ACodec  : onAllocateComponent:6734 mSoftCodecPref:0 componentName:OMX.google.aac.encoder
01-25 17:42:00.181  2629  2924 I OMXClient: MuxOMX ctor
01-25 17:42:00.181  2629  2924 I ACodec  : onAllocateComponent:6703 mSoftCodecPref:0 componentName:
01-25 17:42:00.182  2629  2924 I ACodec  : onAllocateComponent:6734 mSoftCodecPref:0 componentName:OMX.rk.video_encoder.avc
01-25 17:42:00.190  2629  2924 I ACodec  : setupAVCEncoderParameters with [profile: Baseline] [level: Level31]
01-25 17:42:00.191  2629  2924 I ACodec  : [OMX.rk.video_encoder.avc] cannot encode color aspects. Ignoring.
01-25 17:42:00.191  2629  2924 I ACodec  : [OMX.rk.video_encoder.avc] cannot encode HDR static metadata. Ignoring.
01-25 17:42:00.191  2629  2924 I ACodec  : setupVideoEncoder succeeded
01-25 17:42:00.400  2629  2918 I MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: -1 bps and the estimated moov size 3195 bytes
01-25 17:42:00.490  2629  2932 I MPEG4Writer: setStartTimestampUs: 94576541
01-25 17:42:00.490  2629  2932 I MPEG4Writer: Earliest track starting time: 94576541
01-25 17:42:00.597  2629  2629 I Timer-0 : type=1400 audit(0.0:425): avc: denied { write } for name="direction" dev="sysfs" ino=22101 scontext=u:r:system_app:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
01-25 17:42:01.620  2629  2640 I art     : Background sticky concurrent mark sweep GC freed 2823(553KB) AllocSpace objects, 14(280KB) LOS objects, 16% free, 5MB/6MB, paused 5.467ms total 17.673ms
01-25 17:42:30.003  2629  2919 D MPEG4Writer: Audio track stopping
01-25 17:42:30.003  2629  2932 I MPEG4Writer: Received total/0-length (232/0) buffers and encoded 232 frames. - Audio
01-25 17:42:30.003  2629  2933 E MPEG4Writer: The number of recorded samples is 0
01-25 17:42:30.003  2629  2932 I MPEG4Writer: Audio track drift time: 0 us
01-25 17:42:30.003  2629  2919 D MPEG4Writer: Audio track source stopping
01-25 17:42:30.003  2629  2933 W MPEG4Writer: 0-duration samples found: 1
01-25 17:42:30.003  2629  2919 D MPEG4Writer: Audio track source stopped
01-25 17:42:30.003  2629  2933 W MPEG4Writer: 0-duration samples found: 1
01-25 17:42:30.003  2629  2933 I MPEG4Writer: Received total/0-length (0/0) buffers and encoded 0 frames. - Video
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Audio track stopped
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Video track stopping
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Video track source stopping
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Video track source stopped
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Video track stopped
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Duration from tracks range is [0, 29684286] us
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Stopping writer thread
01-25 17:42:30.004  2629  2931 D MPEG4Writer: 0 chunks are written in the last batch
01-25 17:42:30.004  2629  2919 D MPEG4Writer: Writer thread stopped
01-25 17:42:33.351  2629  2919 E AndroidRuntime: FATAL EXCEPTION: Thread-49
01-25 17:42:33.351  2629  2919 E AndroidRuntime: Process: com.frasker.detection, PID: 2629
01-25 17:42:33.351  2629  2919 E AndroidRuntime: java.lang.IllegalStateException: Failed to stop the muxer
01-25 17:42:33.351  2629  2919 E AndroidRuntime: 	at android.media.MediaMuxer.nativeStop(Native Method)
01-25 17:42:33.351  2629  2919 E AndroidRuntime: 	at android.media.MediaMuxer.stop(MediaMuxer.java:245)
01-25 17:42:33.351  2629  2919 E AndroidRuntime: 	at com.serenegiant.usb.encoder.biz.Mp4MediaMuxer.pumpStream(Mp4MediaMuxer.java:143)
01-25 17:42:33.351  2629  2919 E AndroidRuntime: 	at com.serenegiant.usb.encoder.biz.AACEncodeConsumer.encodeBytes(AACEncodeConsumer.java:218)
01-25 17:42:33.351  2629  2919 E AndroidRuntime: 	at com.serenegiant.usb.encoder.biz.AACEncodeConsumer.run(AACEncodeConsumer.java:126)

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
