### ISSUE TITLE
Main Activity variable in the overlay when recording video

### ISSUE THREAD

**Issue by silvioalvim** [jiangdongguo/AndroidUSBCamera#306]
Is there a way to send a value from the main screen to the overlay layer and appear in the recording? I managed to put the date and time (in AbstractUVCCameraHandler.java), but I need this information that is in the Main Activity, but I have no idea how to do this. Thats a value obtained via Bluetooth, changing during video recording. Can someone help me?

**Comment by dudgus0627** [comment]
If you want to overlay something when you record.
Check the OnFrame Callback on  AbastractUVCCameraHandler.java.
you can see the logic to overlay time on frame images before putting them into the encoder.
