### ISSUE TITLE
AAPT: error: duplicate value for resource 'attr/min_value' with config ''.

### ISSUE THREAD

**Issue by fullstact69** [jiangdongguo/AndroidUSBCamera#309]
How can it be fixed?

![Capture](https://user-images.githubusercontent.com/53449197/108892403-c8981680-764a-11eb-86fe-f83397cc08a5.PNG)

**Comment by shiduan** [comment]
原因是com.serenegiant:common:2.12.4内部自定义了attr/orientation，和自己项目冲突后，后来解决是下载到common的源码进行修改，注释该主题和相关的引用
