### ISSUE TITLE
image/webview overlay on record

### ISSUE THREAD

**Issue by habi-kvana** [jiangdongguo/AndroidUSBCamera#310]
instead if TxtOverlay text want to add image or webview as overlay
 
i tried like this....but not capturing overlay in stream.

if (mH264Consumer != null) {
                    // overlay
                    if(isSupportOverlay) {
                        ImageView imgView = new ImageView(mContext);
                        LinearLayout.LayoutParams lp = new LinearLayout.LayoutParams(200, 200);
                        imgView.setImageResource(R.drawable.btn_new_shutter);
                        imgView.setLayoutParams(lp);
                        mFrameLayout.addView(imgView);
//                        TxtOverlay.getInstance().overlay(yuv, new SimpleDateFormat("yyyy-MM-dd EEEE HH:mm:ss").format(newDate()));
                    }

                    mH264Consumer.setRawYuv(yuv, mWidth, mHeight);
                }

**Comment by silvioalvim** [comment]
I think this Overlay should be better explained so that we can use it better. I just need to change the font color, but I don't even know where to start
