### ISSUE TITLE
nativeStopPreview 无响应导致线程阻塞

### ISSUE THREAD

**Issue by zlz3371062** [jiangdongguo/AndroidUSBCamera#311]
所遇问题：能正常打开摄像头并预览，但停止预览失败，一直未返回（停止预览）结束消息

具体描述：
在执行：closeCamera---》stopPreview---》nativeStopPreview(mNativePtr); 方法（.so）后，一直没响应也没返回，
导致 AbstractUVCCameraHandler.handleStopPreview()方法里的 mSync.notifyAll(); 一直没执行，
进而 AbstractUVCCameraHandler.stopPreview()方法一直 thread.mSync.wait(); 。

**Comment by jiangdongguo** [comment]
已经修复。请升级到2.3.5试试

**Comment by Jimmy-J** [comment]
大佬，目前有找到 nativeStopPreview 阻塞的解决方案吗。尝试了现有的解决方案发现还是有概率会阻塞住。
