### ISSUE TITLE
拔掉uvc设备，会造成异常闪退。

### ISSUE THREAD

**Issue by ZSQ970509** [jiangdongguo/AndroidUSBCamera#313]
问题应该在libusb/os/android_usbfs.c文件中的handle_iso_completion 函数，2729行。
这里tpriv->iso_urbs会有为NULL的时候。从而导致了空指针。
if (tpriv->iso_urbs != NULL && urb == tpriv->iso_urbs[i]) {
	urb_idx = i + 1;
	break;
}
https://blog.csdn.net/VNanyesheshou/article/details/100114648

**Comment by jiangdongguo** [comment]
->2.3.6 麻烦再试试
