### ISSUE TITLE
无法预览

### ISSUE THREAD

**Issue by jjfqqaazzx** [jiangdongguo/AndroidUSBCamera#317]
已经连接上摄像头，但是只有160*120分辨率下能显示预览画面，其他分辨率都是黑屏，请问是什么原因啊

**Comment by jiangdongguo** [comment]
由于我这里没有对应的设备，无法重现。

**Comment by Saurabh-WowLabz-Kataria** [comment]
Hey @jiangdongguo I am facing a similar situation with my USB camera device (it has a Sonic Webcam Chipset). I am able to get a preview only in 160 * 120 resolution (the frame rate is around 30-31 in this case, in other cases the frame rate is 1 or 2 and the preview is blank). This occurs on my MediaTek devices (Moto g13 and Poco M4 pro both). @jjfqqaazzx did you find a solution to this? @jiangdongguo what am i missing, or where should I start to look for this?
