### ISSUE TITLE
这个预览流卡顿

### ISSUE THREAD

**Issue by linlipeng557** [jiangdongguo/AndroidUSBCamera#320]
![image](https://user-images.githubusercontent.com/10680739/113860340-7f55ed80-97d8-11eb-8150-1d72a8452148.png)

这个预览流卡顿，如何正确获取预览流来做图像处理呢？

**Comment by jiangdongguo** [comment]
已经有流回调。卡顿问题建议使用MJPEG格式

**Comment by linlipeng557** [comment]
ok
