### ISSUE TITLE
How can I get byte data from uvc camera ?

### ISSUE THREAD

**Issue by bjain409** [jiangdongguo/AndroidUSBCamera#322]
@jiangdongguo @alexeyvasilyev @Metuuu @mafanwei 
I am working on an android app that runs in the background.
I have job which will capture images every 30mins.
How can I just get the byte data from uvcc camera?
There is 2 USB camera attached to android device.

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try

**Comment by RedwanSharafatKabir** [comment]
> @jiangdongguo @alexeyvasilyev @metuuu @mafanwei I am working on an android app that runs in the background. I have job which will capture images every 30mins. How can I just get the byte data from uvcc camera? There is 2 USB camera attached to android device.

Hello @ghost 
Did you solve your issue of capturing image in the background from UVC? If you did, then it would be helpful if you share the procedure.
