### ISSUE TITLE
targetSdkVersion设置成29之后，拔出usb camera后crash

### ISSUE THREAD

**Issue by lanyuqingri** [jiangdongguo/AndroidUSBCamera#326]
您好，我这边在您代码基础上将targetSdkVersion设置成29，然后插入usb camera后可以正常的进行camera的预览等操作，但是拔出camera时出现了crash，具体日志如下：
05-25 21:26:07.608 22307 22307 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-25 21:26:07.609 22307 22307 F DEBUG   : Build fingerprint: 'HUAWEI/TAS-AN00/HWTAS:10/HUAWEITAS-AN00/11.0.0.176C00:user/release-keys'
05-25 21:26:07.609 22307 22307 F DEBUG   : Revision: '0'
05-25 21:26:07.609 22307 22307 F DEBUG   : ABI: 'arm64'
05-25 21:26:07.611 22159 22284 V CameraThread: handleClose:
05-25 21:26:07.612 22307 22307 F DEBUG   : SYSVMTYPE: Maple
05-25 21:26:07.612 22307 22307 F DEBUG   : APPVMTYPE: Art
05-25 21:26:07.612 22307 22307 F DEBUG   : Timestamp: 2021-05-25 21:26:07+0800
05-25 21:26:07.612 22307 22307 F DEBUG   : pid: 22159, tid: 22298, name: CameraThread  >>> com.jiangdg.usbcamera <<<
05-25 21:26:07.612 22307 22307 F DEBUG   : uid: 10187
05-25 21:26:07.613 22307 22307 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
05-25 21:26:07.613 22307 22307 F DEBUG   : Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x797c1100b4)'
05-25 21:26:07.613 22307 22307 F DEBUG   :     x0  0000000000000000  x1  000000000000571a  x2  0000000000000006  x3  00000079787b68c0
05-25 21:26:07.613 22307 22307 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000038
05-25 21:26:07.613 22307 22307 F DEBUG   :     x8  00000000000000f0  x9  09248a4f68f3fa2e  x10 0000000000000001  x11 0000000000000000
05-25 21:26:07.613 22307 22307 F DEBUG   :     x12 fffffff0fffffbdf  x13 0000000060acfaef  x14 0007ceed175309f6  x15 000016061f5ff191
05-25 21:26:07.613 22307 22307 F DEBUG   :     x16 0000007a0b0af9f8  x17 0000007a0b08f6f0  x18 00000079280c8000  x19 000000000000568f
05-25 21:26:07.613 22307 22307 F DEBUG   :     x20 000000000000571a  x21 00000000ffffffff  x22 0000000000000000  x23 000000797c0b6de8
05-25 21:26:07.613 22307 22307 F DEBUG   :     x24 000000797c0c7080  x25 0000000000000004  x26 0000000000000002  x27 0000007988a72380
05-25 21:26:07.613 22307 22307 F DEBUG   :     x28 0000000000000003  x29 00000079787b6960
05-25 21:26:07.613 22307 22307 F DEBUG   :     sp  00000079787b68a0  lr  0000007a0b044580  pc  0000007a0b0445ac
05-25 21:26:07.613 22307 22307 F DEBUG   : 
05-25 21:26:07.613 22307 22307 F DEBUG   : backtrace:
05-25 21:26:07.613 22307 22307 F DEBUG   :       #00 pc 00000000000705ac  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 084953f8f5198acc841653c0a2c76779)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #01 pc 00000000000d0c7c  /apex/com.android.runtime/lib64/bionic/libc.so (__fortify_fatal(char const*, ...)+116) (BuildId: 084953f8f5198acc841653c0a2c76779)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #02 pc 00000000000d03b0  /apex/com.android.runtime/lib64/bionic/libc.so (HandleUsingDestroyedMutex(pthread_mutex_t*, char const*)+52) (BuildId: 084953f8f5198acc841653c0a2c76779)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #03 pc 00000000000d0214  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+148) (BuildId: 084953f8f5198acc841653c0a2c76779)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #04 pc 0000000000010208  /data/app/com.jiangdg.usbcamera-wD53yFl2fd1vquCYnjf5Sg==/lib/arm64/libusb100.so (BuildId: d3d320d24e295f7658d8c85a9c614c0626b535cd)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #05 pc 000000000000c28c  /data/app/com.jiangdg.usbcamera-wD53yFl2fd1vquCYnjf5Sg==/lib/arm64/libusb100.so (BuildId: d3d320d24e295f7658d8c85a9c614c0626b535cd)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #06 pc 000000000000bcf4  /data/app/com.jiangdg.usbcamera-wD53yFl2fd1vquCYnjf5Sg==/lib/arm64/libusb100.so (libusb_handle_events_timeout_completed+748) (BuildId: d3d320d24e295f7658d8c85a9c614c0626b535cd)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #07 pc 000000000000c414  /data/app/com.jiangdg.usbcamera-wD53yFl2fd1vquCYnjf5Sg==/lib/arm64/libusb100.so (libusb_handle_events+44) (BuildId: d3d320d24e295f7658d8c85a9c614c0626b535cd)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #08 pc 0000000000011e24  /data/app/com.jiangdg.usbcamera-wD53yFl2fd1vquCYnjf5Sg==/lib/arm64/libuvc.so (_uvc_handle_events+132) (BuildId: bbd55feb65914680ce546556f4819427a6cc0cfd)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #09 pc 00000000000cf6f0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 084953f8f5198acc841653c0a2c76779)
05-25 21:26:07.614 22307 22307 F DEBUG   :       #10 pc 00000000000720e8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 084953f8f5198acc841653c0a2c76779)

看您最近提交有关于拔出会crash相关问题的修复，是否可以帮忙看些这个问题，非常感谢

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
