### ISSUE TITLE
setDefaultFrameFormat should be call before initMonitor

### ISSUE THREAD

**Issue by tang9716** [jiangdongguo/AndroidUSBCamera#329]
setDefaultFrameFormat should be call before initMonitor

**Comment by bandrarom** [comment]
did you fix it

**Comment by AndroidBody** [comment]
mUSBMonitor no init:

public void setDefaultFrameFormat(int format) {
        if(mUSBMonitor != null) {
            throw new IllegalStateException("setDefaultFrameFormat should be call before initMonitor");
        }
        this.mFrameFormat = format;
 }

update:

mUSBMonitor  init ->setDefaultFrameFormat
  @Override
  public USBMonitor getUSBMonitor() {
      mCameraHelper.setDefaultFrameFormat(UVCCameraHelper.FRAME_FORMAT_MJPEG);
      return mCameraHelper.getUSBMonitor();
  }

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
