### ISSUE TITLE
It is not working on Android version 11

### ISSUE THREAD

**Issue by KanwalKhan-20** [jiangdongguo/AndroidUSBCamera#330]
It is connecting but preview is unavailable

**Comment by ltrhao-wxh** [comment]
Yes, I have the same problem.

**Comment by ltrhao-wxh** [comment]
Is there any solution?

**Comment by EworkitSrl** [comment]
have you solve it

**Comment by ashrafulislamdolon** [comment]
**@EworkitSrl**  facing the same problem..have you solved it yet??

**Comment by KanwalKhan-20** [comment]
Not yet
I have implemented another library

**Comment by ashrafulislamdolon** [comment]
@KanwalKhan-20 can u please share the details?

**Comment by ashrafulislamdolon** [comment]
@KanwalKhan-20 please share the details about the library

**Comment by Allan-Nava** [comment]
Any news?

**Comment by KanwalKhan-20** [comment]
I have tested another library on updated versions and it is not working on
Android 11
Sorry for the inconvenience.

**Comment by JulesD29** [comment]
Any news here ?

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try

**Comment by KanwalKhan-20** [comment]
Hi @jiangdongguo  
Where to add this line.
Because after adding it in gradle I am getting duplicate error.

**Comment by JulesD29** [comment]
Hi @KanwalKhan-20, I had to unload old module to make it work and to comment the part :

    implementation("com.serenegiant:common:${commonLibVersion}") {
        exclude module: 'support-v4'
    }

I don't know if it's a good thing, @jiangdongguo is this the right way ?

**Comment by KanwalKhan-20** [comment]
Hi @JulesD29 
![image](https://user-images.githubusercontent.com/41869999/189620731-59c89b48-920c-4829-adb2-d2469e7a3f42.png)
If I am doing this then where I need to add
 implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7'

Thanks for your support

**Comment by KanwalKhan-20** [comment]
> Hi @KanwalKhan-20, I had to unload old module to make it work and to comment the part :
> 
> ```
> implementation("com.serenegiant:common:${commonLibVersion}") {
>     exclude module: 'support-v4'
> }
> ```
> 
> I don't know if it's a good thing, @jiangdongguo is this the right way ?

![image](https://user-images.githubusercontent.com/41869999/189623377-436a2ff8-edf6-478c-8bc7-9dbaa1055f11.png)

Getting an error

**Comment by KanwalKhan-20** [comment]
> Hi @KanwalKhan-20, I had to unload old module to make it work and to comment the part :
> 
> ```
> implementation("com.serenegiant:common:${commonLibVersion}") {
>     exclude module: 'support-v4'
> }
> ```
> 
> I don't know if it's a good thing, @jiangdongguo is this the right way ?

![image](https://user-images.githubusercontent.com/41869999/189623639-2751ca5c-f6e7-40d9-8577-4aa35a0b8db1.png)
Getting an error

**Comment by JulesD29** [comment]
Do you imported the github of @jiangdongguo like this ?
    implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.2.7'

And do you add this in your build.gradle(:app) ?
repositories {
    allprojects {
        repositories {
            google()
            jcenter()
            maven { url "https://jitpack.io" }
        }
    }
}

**Comment by KanwalKhan-20** [comment]
I have imported the library.

**Comment by KanwalKhan-20** [comment]
> > Do you imported the github of @jiangdongguo like this (in your build.gradle(:app) in dependencies ? implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.2.7'
> > And do you add this in your build.gradle(:app) ? repositories { allprojects { repositories { google() jcenter() maven { url "https://jitpack.io" } } } }
> 
> No

![image](https://user-images.githubusercontent.com/41869999/189661152-a0c4af21-03d6-4286-91e9-6ffc2e8c9146.png)


![image](https://user-images.githubusercontent.com/41869999/189661214-482401fb-6914-4e40-84d3-97128969d183.png)

**Comment by JulesD29** [comment]
OK, I don't know, but in the ReadMe of @jiangdongguo it says that you have to put these lines :

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

https://github.com/jiangdongguo/AndroidUSBCamera#:~:text=allprojects%20%7B%0A%20%20%20%20repositories%20%7B%0A%20%20%20%20%20%20%20%20google()%0A%20%20%20%20%20%20%20%20jcenter()%0A%20%20%20%20%20%20%20%20maven%20%7B%20url%20%22https%3A//jitpack.io%22%20%7D%0A%20%20%20%20%7D%0A%7D
