### ISSUE TITLE
怎么样才可以边预览画面边播放声音。。

### ISSUE THREAD

**Issue by MAYBreath** [jiangdongguo/AndroidUSBCamera#331]
沈垚的那个USB摄像头做的很不错，边预览边有声音播放，而且不知道采用了技术什么延迟会更低一些
看代码是有音频录制的,但是实在不知道从何下手。。

**Comment by Mehdi-android** [comment]
Hi @MAYBreath , Can you please tell me how did you solve the sound issue?

**Comment by cristiano-linvix** [comment]
Hello @MAYBreath, how to implement audioTrack?

**Comment by HeLiHuang** [comment]
> 解决了，直接加个audioTrack播放就可以了，顺便一提，代码里的比特率设置太低了，一般是44100不是8000，不改播出来的声音会非常奇怪

怎么解决的？哥
