### ISSUE TITLE
Reconnection after unplugging and re-plugging 

### ISSUE THREAD

**Issue by zipswich** [jiangdongguo/AndroidUSBCamera#332]
After a USB camera is unplugged **during streaming**, then plugged back, an app's onConnectDev is called properly, but there is no video streaming or any error.  The only way to start streaming in this case is calling UVCCameraHelper.updateResolution() with a **different** resolution. I want to emphasize the resolution has to be different from the previous one.  Calling UVCCameraHelper.updateResolution() with the same resolution will not work. 
However, everything will be normal if the app exits the activity, then enters it again.  In other words, there is no need to set a different resolution in this case, and the video will start normally with the original resolution.

Is there a way to get around this?

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
