### ISSUE TITLE
How to rotate camera input ? 

### ISSUE THREAD

**Issue by Onemaeus97** [jiangdongguo/AndroidUSBCamera#333]
Hi, has anyone successesed in rotating the camera input? I don't know if it is possible because i can't even find the camera input, is it in bitmap or other format? In which class can i find it ? Thanks!!

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
