### ISSUE TITLE
先将UVCCameraTextureView隐藏，再显示，画面就变黑了

### ISSUE THREAD

**Issue by nisabbar** [jiangdongguo/AndroidUSBCamera#335]
我有个需求，就是要先将UVCCameraTextureView隐藏了，释放资源，然后显示另外的画面，另外的画面显示完了后,，再重新显示UVCCameraTextureView，首次显示是可以的，但是设置了隐藏后，再显示，然后初始化一次，发现UVCCameraTextureView就黑了，这种情况该怎么办？求救~

**Comment by whosmyqueen** [comment]
我也遇到这个问题，你是怎么解决的呢

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
