### ISSUE TITLE
依赖不可用了吗

### ISSUE THREAD

**Issue by potian2016** [jiangdongguo/AndroidUSBCamera#346]
Failed to resolve: com.github.jiangdongguo:AndroidUSBCamera:2.3.6

**Comment by zongzj** [comment]
allprojects {
    repositories {
        google()
        maven { url 'https://gitee.com/liuchaoya/libcommon/raw/master/repository/' }
        jcenter()
    }
}

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
