### ISSUE TITLE
How to compress recorded video file ?

### ISSUE THREAD

**Issue by GopalLR** [jiangdongguo/AndroidUSBCamera#348]
I was recording the video in high resolution(3840x2160) and the video file is generated around 7.5 Mbps but I want to convert it into 5 Mbps so how can I do this?

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try

**Comment by GopalLR** [comment]
[image: image.png]

I updated the Lib version as you mention above but am now getting this
error.
I used latest android studio version and support for Android 12.
