### ISSUE TITLE
java.lang.UnsupportedOperationException: open failed:result=-50 at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204) 

### ISSUE THREAD

**Issue by HM-Houda** [jiangdongguo/AndroidUSBCamera#351]
Hello all,
I encounter this error often. and I failed to resolve it.
I found on the net that it is necessary to have an NDK 14b in order to solve this but it does not work for me.

Any help please
Thank you.

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
