### ISSUE TITLE
在USBCameraActivitiy.java文件中CameraDialog.CameraDialogParent接口无法实现

### ISSUE THREAD

**Issue by Leo-WL** [jiangdongguo/AndroidUSBCamera#352]
作者你好，感谢你提供的usb摄像头代码。
本人在学习的使用过程中，编译时出现了错误，错误如下：
public class USBCameraActivity extends AppCompatActivity implements CameraDialog.CameraDialogParent, CameraViewInterface.Callback {
   Ҳ   com.serenegiant.widget.IAspectRatioView     ļ          (部分错误出现乱码，错误的标志指在CameraDialogParent)
在提供的源码中131行mUVCCameraView.setCallback(this);出现报错提示：Cannot access com.serenegiant.widget.IAspectRatioView

希望作者能帮帮初学者，万分感谢。

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
