### ISSUE TITLE
Could not resolve com.github.jiangdongguo:AndroidUSBCamera:2.3.7.

### ISSUE THREAD

**Issue by androidscx** [jiangdongguo/AndroidUSBCamera#361]
Could not resolve com.github.jiangdongguo:AndroidUSBCamera:2.3.7.
         > Could not parse POM https://jitpack.io/com/github/jiangdongguo/AndroidUSBCamera/2.3.7/AndroidUSBCamera-2.3.7.pom
            > Missing required attribute: dependency groupId

**Comment by Allan-Nava** [comment]
Got the same error

**Comment by xiaodi68tmc** [comment]
Has anyone got a solution?

**Comment by alexander-zou** [comment]
same error

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
