### ISSUE TITLE
setOnPreviewFrameListener 返回的数据是NV21吗

### ISSUE THREAD

**Issue by 217fan** [jiangdongguo/AndroidUSBCamera#364]
将setOnPreviewFrameListener拿到的数据传给推流方法，拉流时画面花屏，所以想问一下怎么判断/设置返回的数据格式

**Comment by Clark-caipeiyuan** [comment]
收到了，谢谢！

**Comment by heaveninfosoft** [comment]
@Clark-caipeiyuan bro can you help me for target sdk>=30

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.

**Comment by ShshyDevooo** [comment]
请问解决了吗。目前我也遇到这问题，画面花屏。sdk版本是3.2.6。回调中返回的数据格式是NV21但是还是出现花屏

**Comment by jiangdongguo** [comment]
是直接拿到h264出现花屏，还是nv21，如果是nv21那么需要排差你的颜色合适转换和编码器参数是否正确
