### ISSUE TITLE
How to Set Record Duration 

### ISSUE THREAD

**Issue by dinhtung249** [jiangdongguo/AndroidUSBCamera#368]
Good day sir!
`RecordParams params = new RecordParams();
                    params.setRecordPath(videoPath);
                    params.setRecordDuration(0);                        // 0,do not cut save
                    params.setVoiceClose(mSwitchVoice.isChecked());    // is close voice
		    params.setSupportOverlay(true); 
                    .....`

I am wanna auto save each 5 min, so what should I do. I'm try change value 0 in `params.setRecordDuration(0);`  to 300 000 and 60000 and 5 but only one video file saved. Did I mistake something, plz help me. 
Thank sir !

**Comment by wesoho** [comment]
see here，https://github.com/jiangdongguo/AndroidUSBCamera/issues/358
