### ISSUE TITLE
不使用预览，无法获取相机数据

### ISSUE THREAD

**Issue by cjcj125125** [jiangdongguo/AndroidUSBCamera#371]
您好，我们需求中不显示相机预览界面，只需拿到yuv数据，但是我尝试修改，出了一些问题，求助

**Comment by hzhou81** [comment]
你把预览界面setVisibility(INVISIBLE）不就好了。

**Comment by jiangdongguo** [comment]
Please update to implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.1.7', and have a try
