### ISSUE TITLE
画面卡在第一帧BufferQueue has been abandoned

### ISSUE THREAD

**Issue by androidscx** [jiangdongguo/AndroidUSBCamera#378]
画面卡在第一帧，报错如下BufferQueueProducer: [SurfaceTexture-1-4466-2] dequeueBuffer: BufferQueue has been abandoned，Surface: dequeueBuffer failed (No such device)，解决方法目测是https://blog.csdn.net/YoungHong1992/article/details/84324965这个里面的，我没找到改的地方，希望作者看看

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
