### ISSUE TITLE
libUVCCamera.so 停止预览概率出现jni崩溃

### ISSUE THREAD

**Issue by androidscx** [jiangdongguo/AndroidUSBCamera#383]
#15 pc 0000000000013e60 /data/app/org.geer2.endoscope-1/lib/arm64/libUVCCamera.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+120) [arm64-v8a::26cb168cbbc90392bcc094ea6e47c5ad]

**Comment by androidscx** [comment]
问题解决了，重新打UVC的so文件包

**Comment by liu408309046** [comment]
> 问题解决了，重新打UVC的so文件包

兄弟，我也遇到这个问题，能给个重新打好的包吗
