### ISSUE TITLE
作者您好：预览过程中拔掉usb摄像头会卡住

### ISSUE THREAD

**Issue by gudongjue** [jiangdongguo/AndroidUSBCamera#390]
预览中拔除摄像头会卡住，卡住情况如下：
onDettachDev->closeCamera->close->stopPreview->handleStopPreview->stopPreview->nativeStopPreview(这里面卡住了导致再插上摄像头还是有问题）

**Comment by jiangdongguo** [comment]
哪个分支？应该是崩了

**Comment by gudongjue** [comment]
master分支，预览中拔除摄像头会卡住，导致再插入摄像头也没法正常使用。

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
