### ISSUE TITLE
怎么适配更高的versionTarget

### ISSUE THREAD

**Issue by ColaHJ** [jiangdongguo/AndroidUSBCamera#391]
只能27吗更高的话会崩溃

**Comment by jiangdongguo** [comment]
你用release_3.0_alpha分支试试，我拿下崩溃日志

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try. 已解决

**Comment by JaelynWuJionglin** [comment]
versionTarget  >27 的时候，初次启动Demo，无法弹出设备授权弹窗，无法开启预览。
