### ISSUE TITLE
Scoped Storage support

### ISSUE THREAD

**Issue by snachmsm** [jiangdongguo/AndroidUSBCamera#392]
Inside USBMonitor there is a [`getDeviceList`](https://github.com/jiangdongguo/AndroidUSBCamera/blob/326eddfa8ef2f6eb2e95bbcda7843f0afcd18c5e/libusbcamera/src/main/java/com/serenegiant/usb/USBMonitor.java#L309) method, inside which we have hardcoded path do `failed_devices` file. This path isn't available on devices with enabled Scoped Storage, thus there may be a lot of `IOException` in log. Possible fixes:

- use path inside [Scoped Storage of app](https://developer.android.com/about/versions/11/privacy/storage#app-specific-external)
- remove [printStackTrace](https://github.com/jiangdongguo/AndroidUSBCamera/blob/326eddfa8ef2f6eb2e95bbcda7843f0afcd18c5e/libusbcamera/src/main/java/com/serenegiant/usb/USBMonitor.java#L325)
- inside UVCCameraHelper we have declared [`ROOT_PATH`](https://github.com/jiangdongguo/AndroidUSBCamera/blob/2fd133bd9f19b0eeb6c594f1c8f434dd6f844dc6/libusbcamera/src/main/java/com/jiangdg/usbcamera/UVCCameraHelper.java#L30) - it's widely used in app, but not in method mentioned above. Devs may change this value easily using reflection, but still it isn't used everywhere and won't help for described problem...

**Comment by jiangdongguo** [comment]
please git checkout to release_3.0_alpha， and try again
