### ISSUE TITLE
无法添加依赖

### ISSUE THREAD

**Issue by YXyjt** [jiangdongguo/AndroidUSBCamera#393]
我按照步骤还是依赖添加失败是咋回事
工程的gradle
![g1](https://user-images.githubusercontent.com/26210178/159601983-7d6fa98b-6a3f-495a-b694-c7aa2032bb9e.png)

项目的gradle
![g2](https://user-images.githubusercontent.com/26210178/159601992-2f48ebf8-75e6-44f7-ada3-818a9e3c5d8b.png)

**Comment by jiangdongguo** [comment]
libcommon 去掉
