### ISSUE TITLE
rk3288 board system crash and restart

### ISSUE THREAD

**Issue by mking123456** [jiangdongguo/AndroidUSBCamera#396]
I runned this demo on rk3288 board for a while, it caused system crash and restart,this board android version is 7.1.2  , I cannot checked out any logs, does any one had this problem ? do you have any solution?

**Comment by jiangdongguo** [comment]
hi  please checkout to release_3.0_alpha, and i capture the crash logs~Thanks~

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
