### ISSUE TITLE
how to keep connecting camera?

### ISSUE THREAD

**Issue by chanakamendi** [jiangdongguo/AndroidUSBCamera#397]
if  user close app and reopen the app , it show connecting message .but not show camera preview . how to fix this?

**Comment by dinhtung249** [comment]
check OnDeviceConnectListener#onConnect You need reopen and start preview here.

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.

**Comment by davidZemingo** [comment]
How i subscribe to `OnDeviceConnectListener` 
@jiangdongguo

**Comment by jiangdongguo** [comment]
update to 3.3.3
