### ISSUE TITLE
How to achieve Video Stabilization using this library.

### ISSUE THREAD

**Issue by SreeniMannem** [jiangdongguo/AndroidUSBCamera#400]
HI Dude, thanks for your effort and i am able to do stream using your library and its working like charm!!!. I have observed few minor issues while using this by day by day. One main thing want to discuss on this is, **video stabilization**. We are able to achieve video stabilization through device camera, but when it comes to external UVC we are unable to achieve this. 

Could you please throw some light on this **video stabilization in UVC Cameras** and help us to achieve this through this library.

If already implemented this in it, please let me know where to find out it.

Thanks in advance.

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
