### ISSUE TITLE
Hot to remove date and time from video

### ISSUE THREAD

**Issue by Kiru3014** [jiangdongguo/AndroidUSBCamera#401]
Hi Team Help to know how to remove date and time in recorded video

![image](https://user-images.githubusercontent.com/36956488/167086558-418d038c-876f-41c5-a7f1-3adefd3f0a64.png)

**Comment by Kiru3014** [comment]
got solution so closing isseu

**Comment by benjarn374** [comment]
it would be nice to post about your solution.
