### ISSUE TITLE
根据描述还是无法依赖到

### ISSUE THREAD

**Issue by WanMMao** [jiangdongguo/AndroidUSBCamera#405]
buildscript {
    repositories {
        maven {
            allowInsecureProtocol=true
            url 'http://raw.github.com/saki4510t/master/repository/' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.0.4"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

implementation 'com.github.jiangdongguo:AndroidUSBCamera:2.3.8'

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.
