### ISSUE TITLE
如何加入IbuttonCallback在程序里？

### ISSUE THREAD

**Issue by Christina-ko** [jiangdongguo/AndroidUSBCamera#415]
您好，我的相机上有个按钮可以拍照使用的，可是当我加入Ibutton callback时， 我的preview不能浏览，也会自动闪退。请问有谁遇过一样的问题呢？

**Comment by jiangdongguo** [comment]
Please update to new (3.0), and have a try.

**Comment by Christina-ko** [comment]
Hi jiangdong, 

Thanks for your reply. How can I update it to 3.0 ?
I am able to get the IbuttonCallback signal when I clicked the button on UVC camera and get liveView. I am using uvcCamera to preview and detect the buttonCallback . However, with this library , I am not able to get singleshot of image. Can you guide me how to captureStillImage with uvccamera?
