### ISSUE TITLE
帧率过低怎么处理呢？

### ISSUE THREAD

**Issue by daxiaaaaaaaaaaaaa** [jiangdongguo/AndroidUSBCamera#419]
720*1080的视频 帧率 只有16左右 怎么样能提升到30左右

**Comment by daxiaaaaaaaaaaaaa** [comment]
720*1080的视频 有办法 能达到 25 以上吗

**Comment by daxiaaaaaaaaaaaaa** [comment]
求大佬帮忙帮忙

**Comment by jiangdongguo** [comment]
跟你的设备性能和摄像头有关系吧，我这边能够达到31fps

**Comment by daxiaaaaaaaaaaaaa** [comment]
小视频可以达到，如果是720*1080则达不到，只有24fp左右，同样的摄像头，使用厂家的SDK，可以达到30fps，厂家也是使用UVC协议，只是不是通用的。现在为了兼容所有厂家的设备，所以使用了你的库，是不是咱们这块采样方式有区别？还有优化空间嘛？

**Comment by daxiaaaaaaaaaaaaa** [comment]
目前我这款摄像头 厂家是有提供SDK的 也是采用UVC协议，720*1080的 可以达到30 FPS，但是有的厂家不提供SDK，所以为了兼容所有厂家的设备，采用了您的开源库，但是就是无法达到30fps。

**Comment by daxiaaaaaaaaaaaaa** [comment]
错了 是720*1280

**Comment by jiangdongguo** [comment]
你用的是哪个版本？

**Comment by daxiaaaaaaaaaaaaa** [comment]
我就是昨天从github拉下来的代码，然后直接跑的demo测试，这是最新的版了吧

**Comment by jiangdongguo** [comment]
你把日志发我看看 在Android/data目录下  765067602@qq.com

**Comment by daxiaaaaaaaaaaaaa** [comment]
已发

**Comment by jiangdongguo** [comment]
2022-07-12 10:14:40.775 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 29 fps
2022-07-12 10:14:41.789 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 27 fps
2022-07-12 10:14:42.799 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 26 fps
2022-07-12 10:14:43.826 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 27 fps
2022-07-12 10:14:44.842 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 29 fps
2022-07-12 10:14:45.871 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 28 fps
2022-07-12 10:14:46.893 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 26 fps
2022-07-12 10:14:47.904 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 28 fps
2022-07-12 10:14:48.907 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 27 fps
2022-07-12 10:14:49.921 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 28 fps
2022-07-12 10:14:50.936 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 28 fps
2022-07-12 10:14:51.954 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 28 fps
2022-07-12 10:14:52.984 I/JJCamera: Thread: main
++++++++Info->RenderManager###camera render frame rate is 27 fps

**Comment by daxiaaaaaaaaaaaaa** [comment]
真实的视频 没达到的呢？你可以看下我发给你的视频 查看详情

**Comment by daxiaaaaaaaaaaaaa** [comment]
详细信息 只有22fps

**Comment by jiangdongguo** [comment]
录制视频跟预览是两码事吧

**Comment by daxiaaaaaaaaaaaaa** [comment]
嗯，我们的需求是 需要视频的详细信息 能达到 30帧/秒 左右，这个还有提升空间吗

**Comment by daxiaaaaaaaaaaaaa** [comment]
我观察了预览的时候 是有26 27 28 29左右，开始录制的时候就马上降下来了

**Comment by jiangdongguo** [comment]
你换个性能好点的设备接入摄像头试试，我的录制视频也有29fps

**Comment by jiangdongguo** [comment]
这个跟硬编码器性能，设置的帧率，有关系

**Comment by daxiaaaaaaaaaaaaa** [comment]
好的，720*1280哦 你那边有29左右吗？  奇怪的是 用厂家的SDK 确实能达到30fps，是不是和采样方式有关系明晚观察了咱们这个采样方式应该是边录制 边编码，视频逐渐变大的过程。

**Comment by liyx2018** [comment]
> 这个跟硬编码器性能，设置的帧率，有关系

大佬  我预览时，帧率只有10  然后换了其他摄像头，帧率可以达到30 那是不是说明我这个帧率是10的摄像头有问题  怎么能让这个摄像头预览帧率也达到30呢
