### ISSUE TITLE
拔出UVCCamera 时，奔溃了

### ISSUE THREAD

**Issue by joyhonest** [jiangdongguo/AndroidUSBCamera#420]
当targetSDK 设定为30 时。  添加了摄像头权限，并且在代码中提请动态获取权限，可以正常出图，但当拔出摄像头时，奔溃了。 提示 “pthread_mutex_lock called on a destroyed mutex”
另外，当targetSDK 设定为31 时，修改  PendingIntent.getBroadcast ，添加 PendingIntent.FLAG_IMMUTABLE 可以编译运行。  但当弹出 权限弹框 选择确定后。 final UsbDevice device = intent.getParcelableExtra(UsbManager.EXTRA_DEVICE); 返回 null.   

各位大侠有遇到同样的问题吗？

**Comment by jiangdongguo** [comment]
你用的哪个版本？

**Comment by joyhonest** [comment]
版本是 2.3.7

**Comment by jiangdongguo** [comment]
你试试 3.1.1，目前不能直接依赖，需要下载下来跑

**Comment by jiangdongguo** [comment]
迟点我再发布到jitpack，这个平台无法打包本地aar，有点坑

**Comment by joyhonest** [comment]
把3.1版本的 libuvc.so  覆盖到2.3版本的旧文件，即可解决崩溃。

**Comment by heaveninfosoft** [comment]
@joyhonest @jiangdongguo    versionTarget = 30 or    versionTarget = 31 nothing work always black on work on    versionTarget = 27
