### ISSUE TITLE
Native 层内存泄露的问题

### ISSUE THREAD

**Issue by Jimmy-J** [jiangdongguo/AndroidUSBCamera#421]
感谢大佬提供这么好用的库，目前这个库相比于 UVCCamera 来说 bug 少太多了。目前反复打开关闭，发现这个内存泄露的问题没有处理，希望大佬可以参照这个 issues 在 addCaptureFrame 添加一下 recycle_frame [https://github.com/saki4510t/UVCCamera/issues/259](Native Memory leak)。我添加后重新编译 so 再测试发现内存占用少了很多，原本反复打开关闭 1 小时后会占用 100MB 这样，目前一小时就 10 多 MB。24 小时 40 MB（还是有小的泄露问题，暂时没找到原因）

**Comment by jiangdongguo** [comment]
好的 感谢！

**Comment by jiangdongguo** [comment]
3.1.8

**Comment by Jimmy-J** [comment]
🎉
