### ISSUE TITLE
MultiCameraActivity这里回调是不是写错了

### ISSUE THREAD

**Issue by liu408309046** [jiangdongguo/AndroidUSBCamera#441]
![image](https://user-images.githubusercontent.com/20944115/186569337-7fd4016f-0070-4fb7-bd87-300db13965e6.png)

**Comment by jiangdongguo** [comment]
哪里有问题？

**Comment by rahchen** [comment]
```
 onCameraDisConnected(this)
```
Fragment版正常，Activity版直接断联

**Comment by jiangdongguo** [comment]
除了clear有点不同(可能漏掉了，其他一样的)

    override fun clear() {
        mCameraMap.values.forEach {
            it.closeCamera()
        }
        mCameraMap.clear()
        mCameraClient?.unRegister()
        mCameraClient?.destroy()
        mCameraClient = null
    }

**Comment by liu408309046** [comment]
3.2.7   onConnectDev内还是 onCameraDisConnected(this)

**Comment by jiangdongguo** [comment]
哦哦  写错了 下个版本修复
