### ISSUE TITLE
How to exact frame ?

### ISSUE THREAD

**Issue by dFuong** [jiangdongguo/AndroidUSBCamera#444]
Can you help me about getting inputFrame ?
Please help me?

**Comment by jiangdongguo** [comment]
inputFrame ?What does mean?

**Comment by dFuong** [comment]
I want to process frame by Opencv so I need to exact frame.
I doesn't find out function getting frame.

**Comment by jiangdongguo** [comment]
In CameraFragment or CameraActivity, you can use addPreviewDataCallBack to get NV21 bytes!

**Comment by dFuong** [comment]
Thank you, I'll try it.
Best day for you.

**Comment by jiangdongguo** [comment]
It's ok. Regards!

**Comment by ThuyKhanh** [comment]
Hello there,
I added addPreviewDataCallBack as below code but the callback is never called. Could you plz help ?
override fun onCameraConnected(camera: MultiCameraClient.Camera) {
        for ((position, cam) in mAdapter.data.withIndex()) {
            if (cam.getUsbDevice().deviceId == camera.getUsbDevice().deviceId) {
                val textureView = mAdapter.getViewByPosition(position, R.id.multi_camera_texture_view)
                cam.openCamera(textureView, getCameraRequest())
                cam.addPreviewDataCallBack(previewDataCallBack)
                cam.setCameraStateCallBack(this)
                break
            }
        }
