### ISSUE TITLE
高通骁龙CPU的平板上，录像文件出现绿屏

### ISSUE THREAD

**Issue by wesoho** [jiangdongguo/AndroidUSBCamera#448]
在手机和其他CPU的平板上测试录像正常，但是在几台采用高通骁龙CPU的平板上，无一例外，录像文件出现绿屏问题。
这个问题有没有人遇到过？应该从什么地方入手解决？

**Comment by jiangdongguo** [comment]
如果你没开gles，就是编码器颜色格式转换问题，看下你的编码器支持哪种格式，然后指定输出格式，再将摄像头的nv21转成这种格式

**Comment by wesoho** [comment]
确实开了gles，应该从哪里入手检查问题？

**Comment by jiangdongguo** [comment]
录屏 是没有摄像头画面吗？还是花屏？

**Comment by wesoho** [comment]
摄像头显示正常，录像的时候录出来的画面是绿屏，隐约可以看到几个从左到右排列的重复图像

**Comment by wesoho** [comment]
最终修改； libuvccamera java/com/serenegiant/encoder/biz/H264EncodeConsumer.java 
原格式 format.setInteger(MediaFormat.KEY_COLOR_FORMAT, mColorFormat);
新格式 format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar);
