### ISSUE TITLE
3.2.8连续拍照后大概率会出现红色变蓝色的问题，请问怎么解决

### ISSUE THREAD

**Issue by liu408309046** [jiangdongguo/AndroidUSBCamera#451]
设置640*480分辨率连续拍照不会出现该问题，但是设置高点的分辨率就会出现隔几次就会出现图片变蓝问题
![1662347371826](https://user-images.githubusercontent.com/20944115/188353345-b37ca842-fc44-4089-b5d8-4d5954ad04f1.png)
![image](https://user-images.githubusercontent.com/20944115/188353371-ad50061e-3d01-445f-8049-c9c250e76447.png)
![image](https://user-images.githubusercontent.com/20944115/188353402-bb323013-03ae-4c57-88d2-a6555d6e3fcc.png)

**Comment by jiangdongguo** [comment]
试了下1280x720 暂时没复现你这个问题

**Comment by liu408309046** [comment]
> 试了下1280x720 暂时没复现你这个问题
调用的是多摄像头的 MultiCameraClient

**Comment by jiangdongguo** [comment]
已修复，master拉到最新

**Comment by liu408309046** [comment]
> 已修复，master拉到最新

解决了 谢谢
