### ISSUE TITLE
抓图

### ISSUE THREAD

**Issue by gxh-apologize** [jiangdongguo/AndroidUSBCamera#46]
您好，我想大概每隔20ms抓一次图，希望得到byte[]，或者bitmap也行，而不是本地文件，请问怎么实现呢？

**Comment by jiangdongguo** [comment]
setOnPreviewFrameListener

**Comment by jiangdongguo** [comment]
setOnPreviewFrameListener

**Comment by z-huabao** [comment]
奇怪！我抓了一张图，byte[] length 是460800，但是图片应该是480x640的，怎么算都不对！
这个byte[]该怎么转化为Bitmap呢？
