### ISSUE TITLE
SurfaceView的回调方法里面的代码并没有执行

### ISSUE THREAD

**Issue by cizkey** [jiangdongguo/AndroidUSBCamera#47]
作者在readme文档里面写must have这些代码.  但是我在调试的过程中发现 , cameraHelper.isCameraOpened() 一直为false, 不管能不能预览到画面, 里面的逻辑并不会走, 
请问这些代码是在什么时候执行的? 

``
    @Override
    public void onSurfaceCreated(CameraViewInterface view, Surface surface) {
        if (!isPreview && cameraHelper.isCameraOpened()) {
            cameraHelper.startPreview(uvcCameraView);
            isPreview = true;
        }
    }

    @Override
    public void onSurfaceDestroy(CameraViewInterface view, Surface surface) {
        if (isPreview && cameraHelper.isCameraOpened()) {
            cameraHelper.stopPreview();
            isPreview = false;
        }
    }
``

**Comment by jiangdongguo** [comment]
SurfaceView被销毁重建时，这里的作用是处理stop->start重新预览
