### ISSUE TITLE
Dependancy issues after adding to project

### ISSUE THREAD

**Issue by eetteri** [jiangdongguo/AndroidUSBCamera#473]
I'm trying to incorporate the lib into a project. After I add
```
implementation 'com.github.jiangdongguo:AndroidUSBCamera:3.2.8' 
```
to build.gradle I start getting following dependancy errors
```
Failed to resolve: com.gyf.immersionbar:immersionbar:3.0.0
Failed to resolve: com.zlc.glide:webpdecoder:1.6.4.9.0
```

Is this my newbieness with Android Studio or what could cause this?

**Comment by jiangdongguo** [comment]
Please update to 3.2.9

**Comment by eetteri** [comment]
Updated to 3.2.9 and the end result is same. Below is the whole list I have in use.

```
    implementation 'com.github.girish3.Vlog:library:v0.4'
    implementation 'com.github.jiangdongguo:AndroidUSBCamera:3.2.9'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation 'io.agora.rtc:full-sdk:3.7.1'
    implementation "androidx.core:core-ktx:+"
```

If AndroidUSBCamera is enabled I still get the errors below and when commented out the errors disappear.

```
Failed to resolve: com.gyf.immersionbar:immersionbar:3.0.0
Failed to resolve: com.zlc.glide:webpdecoder:1.6.4.9.0
````

**Comment by jiangdongguo** [comment]
Add those to your app gradle file:
   
 implementation 'com.gyf.immersionbar:immersionbar:3.0.0'
 implementation "com.zlc.glide:webpdecoder:1.6.4.9.0"

**Comment by jiangdongguo** [comment]
please update to 3.2.10 and have a try.

**Comment by eetteri** [comment]
Bumped the version up to 3.2.10, still the result below.

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/493699/195025755-2a15e79f-687e-4333-8453-64b13b5d19e7.png">

**Comment by jiangdongguo** [comment]
Have your project used Glide or Immersionbar?It seems could not download it, may you can try remove it.

**Comment by eetteri** [comment]
I'm not using Glide or Immersionbar in my project. The dependancies and errors appear only if I add the AndroidUSBCamera to my project. If I comment out AndroidUSBCamera project builds and runs just fine, screenshots below. 

Without AndroidUSBCamera
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/493699/195283423-7ce980b8-edaf-4053-bee9-a2c69cb496a1.png">

With AndroidUSBCamera
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/493699/195283991-16c801b3-46d4-4aef-a6de-681eb17a0e78.png">

**Comment by jiangdongguo** [comment]
implementation 'com.github.jiangdongguo.AndroidUSBCamera:libausbc:3.2.10'


NOT：

implementation 'com.github.jiangdongguo.AndroidUSBCamera:3.2.10'

**Comment by eetteri** [comment]
@jiangdongguo thank you for your patience and help. All works great again.
