### ISSUE TITLE
how to change frame format to mjpeg on version 3.2.8?

### ISSUE THREAD

**Issue by rizkyhhh** [jiangdongguo/AndroidUSBCamera#474]
hello I would like to thank you for the library, its really help me a lot in my research. I wanna ask how to change the frame format from YUV to MJPEG on the 3.2.8 version, I tried to change it manually from CameraUvcStrategy.kt and on UVCCamera.kt directly but it still running on YUV format (I am assuming that because its run on 5-10 fps on 1980x1080 resolution).

**Comment by androidscx** [comment]
It seems that the chip decides whether to output data in YUV format or MJPEG format?

**Comment by rizkyhhh** [comment]
i have tried to commented out the option that the app will choose YUV format, but the app still run on low fps at 1980x1080

**Comment by jiangdongguo** [comment]
Hi, 3.0+ default using MHPEG format, If your device do not support it, it will use YUV. So make sure your device support the MJPEG format first!
