### ISSUE TITLE
Ability to record or capture without preview

### ISSUE THREAD

**Issue by BlueCatSoftware** [jiangdongguo/AndroidUSBCamera#478]
Everything is kinda coupled together making use of the library without preview is unclear, please is it possible to use this library without a preview ?

**Comment by jiangdongguo** [comment]
Of course. But you should do it to use Service and MultiCameraClient by yourself now and maybe next version will support it.

**Comment by BlueCatSoftware** [comment]
Thank you, please can you specify a way i can save a recorded video into phone storage?

**Comment by BlueCatSoftware** [comment]
Nevermind thanks, i got it.
Thanks for your response

**Comment by MattWanjia** [comment]
> Thank you, please can you specify a way i can save a recorded video into phone storage through MultiCameraClient?

Hi. Could you kindly share how you were able to achieve this?
