### ISSUE TITLE
建议开放startVideoRecord()和stopVideoRecord()

### ISSUE THREAD

**Issue by lancewoo** [jiangdongguo/AndroidUSBCamera#48]
感谢蒋工开放代码！
我现在想跟清新的SDK对接，需要把H.264的视频流推送过去，清新的SDK说明 https://github.com/tsinglink/ECSDK/wiki/ECSDK%E5%BC%80%E5%8F%91%E6%8C%87%E5%BC%95#%E5%A4%96%E9%83%A8%E5%AA%92%E4%BD%93%E6%BA%90   发现好像除了录制别无他法，要么就是自己重写AbstractUVCCameraHandler.java，如果开放了startVideoRecord()和stopVideoRecord()接口，是不是扩展也会好点？问题是录制的话，怕时间太长了空间又会不够用。 
还有其他方法么？ 感谢！

**Comment by jiangdongguo** [comment]
目前只是做了个简单版本，复杂功能可能需要自己先改源码，有空我会继续完善它。  已成功更新到2.2.8  谢谢提疑、协助！

**Comment by lancewoo** [comment]
感谢！
