### ISSUE TITLE
Library is crashing - LifecycleOwner

### ISSUE THREAD

**Issue by amglol** [jiangdongguo/AndroidUSBCamera#524]
LifecycleOwner is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

This error only occurs after I add the github library project dependencies and run my app. If I run the app without this library added I do not get this error.

![runErr](https://user-images.githubusercontent.com/17322887/218531118-11fcecd9-973d-4f3e-a501-ed413f7affa6.PNG)

**Comment by jiangdongguo** [comment]
Update to 3.3.3 and have a try
