### ISSUE TITLE
Trying to integrate with Agora.io SDK, struggling to pass frames from AndroidUSBCamera to Agora

### ISSUE THREAD

**Issue by eetteri** [jiangdongguo/AndroidUSBCamera#532]
I'm bit new to android development and struggling to integrate AndroidUSBCamera with Agora SDK. I have demo app that has external usb camera showing temporarily on its own fragment and it works fine. I have also the Agora SDK setup and it feeding (internal camera) video stream into CDN.

To integrate these two, Agora has external video source support so that (to my uderstanding) I just pass SurfaceTexture to Agora that the AndroidUSBCamera library is rendering to the external usb camera.

How should I go about this from AndroidUSBCamera side, can I have offscreen SurfaceTexture that AndroidUSBCamera renders to and how to do that?

EDIT: Thinking a bit more, I guess the most easiest way would be if it is possible to create SurfaceTexture and pass that to AndroidUSBCamera instance to be used as render target. Is that possible?

**Comment by jiangdongguo** [comment]
Yes, you are right, you can use your own surfaceTexture to set it to AUSBC.

**Comment by eetteri** [comment]
> Yes, you are right, you can use your own surfaceTexture to set it to AUSBC.

Could you hint me how do I pass my own SurfaceTexture to ausb instance, I couldn’t figure that out. I have CameraFragment instantiated on my app.

**Comment by eetteri** [comment]
As a someone fairly new to Android dev, I'm bit stuck here and would super appreciate if someone with the know would help out here a bit. I pledge to do blog post of how to integrate this library and agora in a simple app for future newbies struggling with the same thing :)

**Comment by eetteri** [comment]
Still getting back to this. I would sooooooo appreciate if anyone could point/hint which constructor/class I can use to swap my own surfaceTexture to be the render target?

**Comment by eetteri** [comment]
> Yes, you are right, you can use your own surfaceTexture to set it to AUSBC.

Still hoping I could get hint tow to do this...
