### ISSUE TITLE
Video Feed Not Displaying Correctly

### ISSUE THREAD

**Issue by zachary-w-msi** [jiangdongguo/AndroidUSBCamera#538]
Hello,

I'm trying to test this library by building the sample application and I'm seeing weird behavior on the video feed. It seems to be the right data but the colors are incorrect. Is there a setting I need to change for this? Screenshot below. Thanks!
![Screenshot_20230301-084725](https://user-images.githubusercontent.com/60145655/222542793-aa1d25bb-bb22-4d4f-98d8-21e5e01cd81c.png)

Drive Link with video and log files https://drive.google.com/drive/folders/1lNwknMupm7wFfQUb-RpVtx9k5wsvGzqY?usp=sharing

**Comment by jiangdongguo** [comment]
How about closing opengl render？

**Comment by zachary-w-msi** [comment]
I've tried setting RenderMode to NORMAL and I still see the same behavior. Is there another method to close the opengl render?

**Comment by zachary-w-msi** [comment]
Also noticing a lot of E/BLASTBufferQueue: [VRI[MainActivity]#1](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback in Logcat.

**Comment by zachary-w-msi** [comment]
Closing issue seemed to be an issue with the UVC device. It's working now. Thanks @jiangdongguo
