### ISSUE TITLE
Black Screen After Format Change

### ISSUE THREAD

**Issue by RobbieElias** [jiangdongguo/AndroidUSBCamera#627]
Hello,

The app works great when first booted. But if I switch the video format (e.g. 1080p 30FPS YUV to 720p 30FPS YUV), then the preview turns black and no more frames come in. I have to unplug device to make it work again.

I am using a capture card based on the ms2130 chip. I have tested using the USB camera app on the Play Store and it works fine on there.

Appreciate any help!

**Comment by RobbieElias** [comment]
Finally was able to figure it out. I think this could be helpful to some. Change the following lines in the `stream.c` file:

```
case LIBUSB_TRANSFER_ERROR:
	UVC_DEBUG("not retrying transfer, status = %d", transfer->status);
//	MARK("not retrying transfer, status = %d", transfer->status);
//	_uvc_delete_transfer(transfer);
	resubmit = 0;
	break;
```

To:

```
case LIBUSB_TRANSFER_ERROR:
	libusb_clear_halt(strmh->devh->usb_devh, strmh->stream_if->bEndpointAddress);
	UVC_DEBUG("not retrying transfer, status = %d", transfer->status);
//	MARK("not retrying transfer, status = %d", transfer->status);
//	_uvc_delete_transfer(transfer);
	resubmit = 0;
	break;
```

**Comment by JeffZane** [comment]
> Finally was able to figure it out. I think this could be helpful to some. Change the following lines in the `stream.c` file:
> 
> ```
> case LIBUSB_TRANSFER_ERROR:
> 	UVC_DEBUG("not retrying transfer, status = %d", transfer->status);
> //	MARK("not retrying transfer, status = %d", transfer->status);
> //	_uvc_delete_transfer(transfer);
> 	resubmit = 0;
> 	break;
> ```
> 
> To:
> 
> ```
> case LIBUSB_TRANSFER_ERROR:
> 	libusb_clear_halt(strmh->devh->usb_devh, strmh->stream_if->bEndpointAddress);
> 	UVC_DEBUG("not retrying transfer, status = %d", transfer->status);
> //	MARK("not retrying transfer, status = %d", transfer->status);
> //	_uvc_delete_transfer(transfer);
> 	resubmit = 0;
> 	break;
> ```

I have tried this code but it has no effect, any other updates?
