### ISSUE TITLE
如何添加简单滤镜至相机预览（如反色滤镜、灰度图）

### ISSUE THREAD

**Issue by wstown** [jiangdongguo/AndroidUSBCamera#84]
使用本项目实现相机预览的时候，如何添加一些简单的滤镜效果（比如反色、灰度图等）。
Android自带的EffectFactory可以实现灰度图，反色图等简单滤镜，怎么集成到本项目里呢。
刚开始接触opengl，有点懵，求助。

**Comment by 1159658610** [comment]
是指实时预览出来的数据流显示的是灰度图吗?

**Comment by wstown** [comment]
是的，比如可以选择几个简单滤镜，选择反色则显示反色的实时预览；选择灰度图则显示灰度图的实时预览。刚才研究了会openGL的shader，通过UVCCameraTextureView里mDrawer的updateShader方法，直接设置framgent shader，能实现反色和灰度图。还在研究怎么切换回原始的无滤镜的实时预览，resetShader好像没有起作用。
